### ISSUE TITLE
SPDX 3.0 license expressions not supported

### ISSUE THREAD

**Issue by zgtm** [withoutboats/license-exprs#18]
As discussed in https://github.com/rust-lang/cargo/issues/4930, Cargo documents to use SPDX license expressions as found on https://spdx.org/licenses/. However, listed there are the SPDX 3.0 identifiers that are not compatible to the 2.x identifiers that can be parsed with this crate. Thus, I'd suggest to make the capabilities to parse SPDX 3.0 expressions.

I can do that. However, I'm not totally clear, what would be the best way to achieve that.

I see three possibilities of adding the ability to parse for SPDX 3.0 license identifiers:

- Adding capabilities to parse SPDX 3.0 expressions to this crate by adding a version tag to the API and 
  - using the 2.x identifiers as default (backwards compatible)
  - using the 3.0 identifiers as default (backwards compatible, updating all dependent crates to the new identifiers)
  - using the all possible identifiers as default (backwards compatible)
  - using no default value, forcing all dependent crates to update
- Creating a new crate that parses SPDX 3.0 expressions.
- Just replacing the SPDX 2.x identifiers with the SPDX 3.0 identifiers in this crate and consequently dropping support for SPDX 2.x identifiers.

I would suggest the first of these possibilities, with additionally marking the the use of the default value as deprecated.

**Comment by wking** [comment]
I think this repo should track whatever license-list version Cargo
documents (2.4 since rust-lang/cargo#4930).  But we can certainly code
new versions up here.  Once we have something ready to go here, we'll
need to bump the Cargo docs to the new version, update Cargo and its
public docs (there seems to be some lag for this, #4930), and update
crates.io.

I don't think backwards-compat is a big concern, because the SPDX
folks have been good about long deprecation periods (I'm not aware of
any deprecated identifiers that have actually been removed).  Folks
using deprecated identifiers will ideally get warnings from Cargo
and/or crates.io, but can carry on with the old identifiers if they
don't have time to update.

And there's a script in flight with #11 to automate bumps.  @nodakai,
do you expect to have time to get back to that in the next month or
two?

**Comment by nodakai** [comment]
@wking will do my best...!!

**Comment by wking** [comment]
#11 has landed, so once we cut a release here we can move forward with the Cargo and crates.io updates.
